name: Build & Upload MineBackup (Linux)

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake pkg-config libglfw3-dev libgl1-mesa-dev p7zip-full

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release .

    - name: Build MineBackup
      run: cmake --build . --config Release

    - name: 7z Compress Executable
      run: |
        7z a MineBackup-linux.7z MineBackup

    - name: Get latest release
      id: get_release
      uses: actions/github-script@v7
      with:
        script: |
          const releases = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 1,
          });
          if (!releases.data.length) throw 'No releases found';
          const release = releases.data[0];
          core.setOutput('upload_url', release.upload_url);
          core.setOutput('release_id', release.id);

    - name: Upload artifact to latest release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./MineBackup-linux.7z
        asset_name: MineBackup-linux.7z
        asset_content_type: application/x-7z-compressed
